# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d65a0f8ddfa6565d28ee2c9dba7db13daf62cc29468d5ecb80bec7a674bdc0d928cd2d33f7584ac497c1eb29dae34c970de740b85845a347c2f6b1f2f2f2760

test:
  secret_key_base: a541791afc458addce6932eb80c3e4671898e24490d858a902769675c445483d3f7cebc926925dc7a81c506e44d2fe6548c75eeec9f06edf95759a0a6823ffd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
